version: '2.23'

services:
  discord:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: python3 run_discord_bot.py

  agent_api:
    container_name: agent_api
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: python3 main.py
    ports:
      - 8000:8000

  # Production Use only
  guru_api:
    container_name: guru_api
    build:
      context: ./guru_api
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - AGENT_API=http://agent_api:8000
    depends_on:
      - agent_api
    links:
      - agent_api:agent_api
    env_file:
      - .env
    volumes:
      - guru_api_storage:/rails/storage/
    ports:
      - 3000:3000

volumes:
  guru_api_storage: