version: '2.23'

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guru_api
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/kafka/kafka-logs


  # Client for the Guru API
  discord_bot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - guru_api
      - db
      - kafka
      - zookeeper
    links:
      - guru_api:guru_api
    env_file:
      - .env_discord_bot
    volumes:
      - .:/app
    command: python3 run_discord_bot.py

  # Chat Completion by python OpenAI Agents
  # agent_api:
  #   container_name: agent_api
  #   build:
  #     context: .
  #     dockerfile: .devcontainer/Dockerfile
  #   depends_on:
  #     - guru_api
  #   links:
  #     - guru_api:guru_api
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   command: python3 main.py
  #   ports:
  #     - 8000:8000

  # This runs as it's in Production. Modify with caution.
  # primary api backend
  guru_api:
    container_name: guru_api
    build:
      context: ./guru_api
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - AGENT_API=http://agent_api:8000
    env_file:
      - .env
    volumes:
      - ./guru_api:/rails
      - guru_api_storage:/rails/storage/
    ports:
      - 3000:3000
    depends_on:
      - db
      - kafka
      - zookeeper
    links:
      - db:db

  karafka:
    container_name: karafka
    build:
      context: ./guru_api
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - AGENT_API=http://agent_api:8000
        - KAFKA_BROKERS=kafka:9092
        - ZOOKEEPER_URL=zookeeper:2181
    command: ./bin/karafka server
    env_file:
      - .env
    volumes:
      - ./guru_api:/rails
      - guru_api_storage:/rails/storage/
    depends_on:
      - db
      - kafka
      - zookeeper
    links:
      - db:db


volumes:
  guru_api_storage:
  db:
  zookeeper_data:
  kafka_data:
