# TODO: Add ai.py service

version: '2.23'

services:
  discord:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
    command: python3 discord_bot/bot.py
