default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("GURU_API_DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("GURU_API_DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: guru_api_development
  username: guru_api

test:
  <<: *default
  database: guru_api_test
  username: guru_api

production:
  <<: *default
  database: guru_api_production
  username: guru_api
  password: <%= ENV["GURU_API_DATABASE_PASSWORD"] %>
